language: python
python:
  - "2.7"


notifications:
  email:
    on_failure: change # [always|never|change] default: always

before_install:
  # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq


install:
  - pip install param
  - pip install holoviews
  - pip install jinja2 tornado pyzmq matplotlib pillow
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then pip install ipython==5 ipykernel; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then pip install ipython ipykernel; fi
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform

before-script:
  - "echo 'backend : Agg' > $HOME/.matplotlib/matplotlibrc"

script:
  - nosetests --with-doctest --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_imagen_a3bf72b041_3
  - python -m properform Push 47.88.50.110:15554 asdf_imagen_a3bf72b041_3 ./profile_imagen_a3bf72b041_3

 #2017-08-11 14:52:10 modified at 0 #2017-08-11 14:52:16 modified at 1 #2017-08-11 14:52:21 modified at 2 #2017-08-11 14:52:27 modified at 3