language: python
python:
  - "2.7"

notifications:
  email:
    on_failure: change # [always|never|change] default: always

before_install:
  # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq



install:
  - pip install param
  - pip install holoviews
  - pip install jinja2 tornado pyzmq matplotlib pillow
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then pip install ipython==1.0; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then pip install ipython; fi
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform

before-script:
  - "echo 'backend : Agg' > $HOME/.matplotlib/matplotlibrc"

script:
  - nosetests --with-doctest --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_imagen_f29371da32_2
  - python -m properform Push 47.88.50.110:15554 asdf_imagen_f29371da32_2 ./profile_imagen_f29371da32_2
 #2017-08-11 15:03:39 modified at 0 #2017-08-11 15:03:45 modified at 1 #2017-08-11 15:03:51 modified at 2